source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
target 'JKNews' do
  use_frameworks!
  
  pod 'SDWebImage', '~> 3.8.2'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod 'HandyJSON' 

  pod 'PromiseKit', '~> 4.0'

  pod 'JPush'
 
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  
  pod 'RxSwift', '~> 4.0'
  pod 'EVReflection/Moya'
  pod 'RxCocoa', '~> 4.0'
  
 ## pod 'IQKeyboardManagerSwift', '5.0.0'

  pod 'MJExtension', '~> 3.0.13'
  pod 'ActionSheetPicker-3.0' , '~> 2.3.0'

  pod 'NinaPagerView', :git => 'https://github.com/RamWire/NinaPagerView.git'
  pod 'ActionPickerUtils', :git => 'https://github.com/APUtils/ActionPickerUtils.git'

end

